[build]
target = "x86_64-unknown-uefi"

[unstable]
build-std = ["core", "alloc"]

[target.x86_64-unknown-uefi]
# rustflags = ["-Z", "pre-link-args=/subsystem:efi_runtime_driver"]
rustflags = ["-C", "link-args=/debug:dwarf"]
# linker = "ld"