[build]
target = "kernel_target.json"
rustflags = ["-C", "link-arg=-Tkernel/link.x"]

[unstable]
build-std = ["core", "alloc"]

#[target.x86_64-unknown-none]
#linker = "ld.lld"
# rustflags = ["-C", "link-args=/debug:dwarf"]