[workspace]
members = [
    "kernel",
	"kernel_loader",
    "kernel_api/*",
    "boot_image_generator",
    "disk_image_generator",
    "drivers/*"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
