[build]
target = "../driver_target.json"

[unstable]
build-std = ["core"]

# linker = "ld"
# rustflags = ["-C", "link-args=/debug:dwarf"]
# rustflags = ["-C", "link-dead-code"]
# rustflags = ["-C", "lto"]