[build]
target = "x86_64-unknown-linux-musl"

[unstable]
build-std = ["core"]

[target.x86_64-unknown-linux-musl]
# linker = "ld"
# rustflags = ["-C", "link-args=/debug:dwarf"]
# rustflags = ["-C", "link-dead-code"]
# rustflags = ["-C", "lto"]